### ISSUE TITLE
Crash when loss of internet occurs

### ISSUE THREAD

**Issue by AndyHankewycz** [statsig-io/roku-sdk#1]
https://github.com/statsig-io/roku-sdk/blob/a0d300529fb57a1f0bc1635d58383b3594646203/components/statsigsdk/StatsigTask.brs#L124

This is a trap I've come across. When `msg` is `invalid` and it's passed to `parseJSON` on the following line

From Roku's docs, Wait can return `invalid`
https://developer.roku.com/docs/references/brightscript/language/global-utility-functions.md#waittimeout-as-integer-port-as-object-as-object
> Wait will return after timeout milliseconds if no messages are received. In this case, Wait returns a type "invalid".

**Comment by vijaye-statsig** [comment]
cc: @tore-statsig

**Comment by tore-statsig** [comment]
Thanks for the report, we will take a look

**Comment by tore-statsig** [comment]
I havent tested this yet because my roku device is at work, but I think this is all that needs to change (see linked PR).  Since the Roku SDK is copied into your app, you can likely apply this change now without waiting for it to be pushed.

Let me know if this resolves your issue

**Comment by AndyHankewycz** [comment]
Thanks @tore-statsig, we did push a fix for this on our end the other day which I shared with you in the PR
